<PaginaSincro>:
    orientation: 'vertical'
    spacing: 1

    AppActionBar:
        size_hint: (1., 0.1)

    Image:
        source: 'kivy.jpg'

<PaginaCuentas>:
    orientation: 'vertical'
    spacing: 1

    AppActionBar:
        size_hint: (1., 0.1)

    Label:
        text: 'due'

<PaginaInicio>:
    orientation: 'vertical'
    spacing: 1

    AppActionBar:
        size_hint: (1., 0.1)

    Label:
        text: 'applicazione'
