<PaginaCuentas>:
    orientation: 'vertical'
    spacing: 1

    main_cuentas: main_cuentas

    AppActionBar:
        size_hint: (1., 0.1)

    Label:
        text: 'Cuentas'
        size_hint_y: 0.3

    ScrollView:
        pos: 0, 0

        TreeView:
            id: main_cuentas
            hide_root: True
            size_hint_y: None

    BoxLayout:
        orientation: 'horizontal'
        size_hint_y: 0.2

        Button:
            text: 'Agregar'

